---
version: 2
models:
- name: "model_sanity_parent_orchestration_pipeline_1_Join_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__sanity_parent_orchestration_pipeline_1"
  database: "hive_metastore"
  schema: "qa_db_warehouse"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mbkc8nnu__sanity_parent_orchestration_pipeline_1__Join_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy_tmp__mbkc8nnu__sanity_parent_orchestration_pipeline_1__S3Source_1"
    tags:
    - "prophecy_temp"
