---
version: 2
sources:
- name: "alias_spark_catalog_qa_db_warehouse"
  database: "spark_catalog"
  schema: "qa_database"
  config:
    enabled: true
  tables:
  - name: "all_type_non_partitioned"
    columns:
    - name: "c_tinyint"
      dataType:
        type: "TinyInt"
    - name: "c_smallint"
      dataType:
        type: "SmallInt"
    - name: "c_int"
      dataType:
        type: "Integer"
    - name: "c_bigint"
      dataType:
        type: "Bigint"
    - name: "c_float"
      dataType:
        type: "Float"
    - name: "c_double"
      dataType:
        type: "Double"
    - name: "c_string"
      dataType:
        type: "String"
    - name: "c_boolean"
      dataType:
        type: "Boolean"
    - name: "c_array"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_struct"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
  - name: "all_type_partitioned"
    columns:
    - name: "c_tinyint"
      dataType:
        type: "TinyInt"
    - name: "c_smallint"
      dataType:
        type: "SmallInt"
    - name: "c_int"
      dataType:
        type: "Integer"
    - name: "c_bigint"
      dataType:
        type: "Bigint"
    - name: "c_float"
      dataType:
        type: "Float"
    - name: "c_double"
      dataType:
        type: "Double"
    - name: "c_string"
      dataType:
        type: "String"
    - name: "c_boolean"
      dataType:
        type: "Boolean"
    - name: "c_array"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_struct"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
    - name: "p_int"
      dataType:
        type: "Integer"
    - name: "p_string"
      dataType:
        type: "String"
- name: "alias_spark_catalog_qa_database"
  database: "spark_catalog"
  schema: "qa_database"
  config:
    enabled: true
  tables: []
- name: "hive_metastore.qa_database"
  database: "hive_metastore"
  schema: "qa_database"
  config:
    enabled: true
  tables:
  - name: "all_type_partitioned"
    columns:
    - name: "c_tinyint"
      dataType:
        type: "TinyInt"
    - name: "c_smallint"
      dataType:
        type: "SmallInt"
    - name: "c_int"
      dataType:
        type: "Integer"
    - name: "c_bigint"
      dataType:
        type: "Bigint"
    - name: "c_float"
      dataType:
        type: "Float"
    - name: "c_double"
      dataType:
        type: "Double"
    - name: "c_string"
      dataType:
        type: "String"
    - name: "c_boolean"
      dataType:
        type: "Boolean"
    - name: "c_array"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_struct"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
    - name: "p_int"
      dataType:
        type: "Integer"
    - name: "p_string"
      dataType:
        type: "String"
  - name: "all_type_non_partitioned"
    columns:
    - name: "c_tinyint"
      dataType:
        type: "TinyInt"
    - name: "c_smallint"
      dataType:
        type: "SmallInt"
    - name: "c_int"
      dataType:
        type: "Integer"
    - name: "c_bigint"
      dataType:
        type: "Bigint"
    - name: "c_float"
      dataType:
        type: "Float"
    - name: "c_double"
      dataType:
        type: "Double"
    - name: "c_string"
      dataType:
        type: "String"
    - name: "c_boolean"
      dataType:
        type: "Boolean"
    - name: "c_array"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_struct"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
